version: "2"
run:
  tests: true
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - cyclop
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - funlen
    - gocheckcompilerdirectives
    - gochecknoinits
    - gocognit
    - gocritic
    - gocyclo
    - godot
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - grouper
    - ineffassign
    - lll
    - loggercheck
    - makezero
    - mirror
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - perfsprint
    - predeclared
    - promlinter
    - reassign
    - revive
    - sloglint
    - staticcheck
    - testableexamples
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
  settings:
    cyclop:
      max-complexity: 50
      package-average: 10
    errcheck:
      check-type-assertions: false
    exhaustive:
      check:
        - switch
        - map
    funlen:
      lines: 175
      statements: 100
      ignore-comments: true
    gocognit:
      min-complexity: 50
    gocritic:
      settings:
        captLocal:
          paramsOnly: false
        underef:
          skipRecvDeref: false
    gocyclo:
      min-complexity: 50
    gomodguard:
      blocked:
        modules:
          - github.com/golang/protobuf:
              recommendations:
                - google.golang.org/protobuf
              reason: see https://developers.google.com/protocol-buffers/docs/reference/go/faq#modules
          - github.com/satori/go.uuid:
              recommendations:
                - github.com/google/uuid
              reason: satori's package is not maintained
          - github.com/gofrs/uuid:
              recommendations:
                - github.com/google/uuid
              reason: gofrs' package is not go module
    govet:
      enable-all: true
      settings:
        shadow:
          strict: false
    lll:
      line-length: 120
      tab-width: 1
    nakedret:
      max-func-lines: 0
    nestif:
      min-complexity: 20
    nolintlint:
      require-explanation: false
      require-specific: true
      allow-no-explanation:
        - funlen
        - gocognit
        - lll
    revive:
      rules:
        - name: add-constant
          arguments:
            - allowFloats: 0.0,0.,1.0,1.,2.0,2.
              allowInts: 0,1,2
              allowStrs: '""'
              maxLitCount: "3"
          disabled: true
        - name: argument-limit
          arguments:
            - 7
          disabled: false
        - name: atomic
          disabled: false
        - name: banned-characters
          arguments:
            - Ω
            - Σ
            - σ
            - "7"
          disabled: true
        - name: bare-return
          disabled: false
        - name: blank-imports
          disabled: false
        - name: bool-literal-in-expr
          disabled: false
        - name: call-to-gc
          disabled: false
        - name: cognitive-complexity
          arguments:
            - 7
          disabled: true
        - name: comment-spacings
          arguments:
            - mypragma
            - otherpragma
          disabled: true
        - name: confusing-naming
          disabled: true
        - name: confusing-results
          disabled: false
        - name: constant-logical-expr
          disabled: false
        - name: context-as-argument
          arguments:
            - allowTypesBefore: '*testing.T,*github.com/user/repo/testing.Harness'
          disabled: false
        - name: context-keys-type
          disabled: false
        - name: cyclomatic
          arguments:
            - 3
          disabled: true
        - name: datarace
          disabled: false
        - name: deep-exit
          disabled: false
        - name: defer
          arguments:
            - - call-chain
              - loop
          disabled: false
        - name: dot-imports
          disabled: false
        - name: duplicated-imports
          disabled: false
        - name: early-return
          arguments:
            - preserveScope
          disabled: false
        - name: empty-block
          disabled: false
        - name: empty-lines
          disabled: true
        - name: enforce-map-style
          arguments:
            - make
          disabled: true
        - name: error-naming
          disabled: false
        - name: error-return
          disabled: false
        - name: error-strings
          disabled: false
        - name: errorf
          disabled: false
        - name: file-header
          disabled: true
        - name: flag-parameter
          disabled: true
        - name: function-result-limit
          arguments:
            - 4
          disabled: false
        - name: function-length
          arguments:
            - 10
            - 0
          disabled: true
        - name: get-return
          disabled: false
        - name: identical-branches
          disabled: false
        - name: if-return
          disabled: false
        - name: increment-decrement
          disabled: false
        - name: indent-error-flow
          arguments:
            - preserveScope
          disabled: false
        - name: import-alias-naming
          arguments:
            - ^[a-z][a-z0-9]{0,}$
          disabled: false
        - name: imports-blocklist
          arguments:
            - crypto/md5
            - crypto/sha1
          disabled: false
        - name: import-shadowing
          disabled: false
        - name: line-length-limit
          arguments:
            - 80
          disabled: true
        - name: max-public-structs
          arguments:
            - 3
          disabled: true
        - name: modifies-parameter
          disabled: false
        - name: modifies-value-receiver
          disabled: false
        - name: nested-structs
          disabled: false
        - name: optimize-operands-order
          disabled: false
        - name: package-comments
          disabled: false
        - name: range
          disabled: false
        - name: range-val-in-closure
          disabled: false
        - name: range-val-address
          disabled: false
        - name: receiver-naming
          disabled: false
        - name: redundant-import-alias
          disabled: false
        - name: redefines-builtin-id
          disabled: false
        - name: string-of-int
          disabled: false
        - name: string-format
          arguments:
            - - core.WriteError[1].Message
              - /^([^A-Z]|$)/
              - must not start with a capital letter
            - - fmt.Errorf[0]
              - /(^|[^\.!?])$/
              - must not end in punctuation
            - - panic
              - /^[^\n]*$/
              - must not contain line breaks
          disabled: false
        - name: struct-tag
          arguments:
            - json,inline
            - bson,outline,gnu
          disabled: false
        - name: superfluous-else
          arguments:
            - preserveScope
          disabled: false
        - name: time-equal
          disabled: true  # Disabled: behaves inconsistently across architectures (arm64 vs amd64)
        - name: time-naming
          disabled: false
        - name: var-naming
          arguments:
            - - ID
            - - VM
            - - upperCaseConst: true
          disabled: false
        - name: var-declaration
          disabled: false
        - name: unconditional-recursion
          disabled: false
        - name: unexported-naming
          disabled: false
        - name: unexported-return
          disabled: false
        - name: unhandled-error
          arguments:
            - fmt.Printf
            - fmt.Fprintf
            - fmt.Fprint
            - fmt.Fprintln
            - bytes.Buffer.Write
            - bytes.Buffer.WriteByte
            - bytes.Buffer.WriteString
            - bytes.Buffer.WriteRune
            - strings.Builder.WriteString
            - strings.Builder.WriteRune
            - strings.Builder.Write
          disabled: false
        - name: unnecessary-stmt
          disabled: false
        - name: unreachable-code
          disabled: false
        - name: unused-parameter
          arguments:
            - allowRegex: ^_
          disabled: false
        - name: unused-receiver
          arguments:
            - allowRegex: ^_
          disabled: true
        - name: useless-break
          disabled: false
        - name: waitgroup-by-value
          disabled: false
    rowserrcheck:
      packages:
        - github.com/jmoiron/sqlx
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - lll
        source: ^//\s*go:generate\s
      - linters:
          - godot
        source: (noinspection|TODO)
      - linters:
          - gocritic
        source: //noinspection
      - linters:
          - errorlint
        source: ^\s+if _, ok := err\.\([^.]+\.InternalError\); ok {
      - linters:
          - bodyclose
          - dupl
          - funlen
          - goconst
          - gosec
          - govet
          - noctx
          - wrapcheck
        path: _test\.go
      - linters:
          - revive
        path: drivers/json/
        text: var-naming
      - linters:
          - revive
        text: "avoid package names that conflict with Go standard library package names"
    paths:
      - cli/output/jsonw/internal/jcolorenc
      - libsq/core/diffdoc/internal/go-udiff
      - cli/output/tablew/internal
      - libsq/core/lg/devlog/tint
      - libsq/core/upgrademu
      - scratch
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 3
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    gofumpt:
      module-path: github.com/neilotoole/sq
      extra-rules: true
  exclusions:
    generated: lax
    paths:
      - cli/output/jsonw/internal/jcolorenc
      - libsq/core/diffdoc/internal/go-udiff
      - cli/output/tablew/internal
      - libsq/core/lg/devlog/tint
      - libsq/core/upgrademu
      - scratch
      - third_party$
      - builtin$
      - examples$
