before:
  hooks:
    - go mod tidy

builds:
  - builder: prebuilt
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    goamd64:
      - v1
    ignore:
      - goos: windows
        goarch: arm64
    prebuilt:
      path: dist-{{ .Os }}/sq_{{ .Os }}_{{ .Arch }}{{ with .Amd64 }}_{{ . }}{{ end }}/sq{{ .Ext }}
    binary: sq

archives:
  -
    name_template: "{{.ProjectName}}-{{ .Version }}-{{.Os}}-{{.Arch}}"
    replacements:
      darwin: macos
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-snapshot"
changelog:
  skip: true

release:
  github:
    owner: neilotoole
    name: sq
  draft: false
  prerelease: auto

brews:
  -
    homepage: "https://github.com/neilotoole/sq"
    description: "sq is a swiss army knife for data"
    license: MIT
    tap:
      owner: neilotoole
      name: homebrew-sq

    commit_author:
      name: neilotoole
      email: neilotoole@apache.org

    install: |
      bin.install "sq"
    test: |
      system "#{bin}/sq --version"

scoop:
  bucket:
    owner: neilotoole
    name: sq
  homepage: "https://sq.io"
  description: "sq is a swiss army knife for data"
  license: MIT
  commit_author:
    name: neilotoole
    email: neilotoole@apache.org

nfpms:
  -
    formats:
      - apk
      - deb
      - rpm
      - termux.deb
      - archlinux
    vendor: "neilotoole"
    maintainer: "neilotoole <neilotoole@apache.org>"
    homepage: "https://sq.io"
    description: "sq is a swiss army knife for data"
    license: "MIT"

furies:
  # Upload deb and rpm to fury.io. Requires that envar $FURY_TOKEN be set.
  - account: neilotoole
