// Package lga ("log attribute") holds constants for log attribute
// names.
package lga

const (
	Alt       = "alt"
	Cmd       = "cmd"
	Col       = "column"
	Count     = "count"
	Commit    = "commit"
	Cleanup   = "cleanup"
	DB        = "db"
	DBType    = "db_type"
	Driver    = "driver"
	DefaultTo = "default_to"
	Elapsed   = "elapsed"
	Env       = "env"
	Err       = "error"
	From      = "from"
	Flag      = "flag"
	Handle    = "handle"
	Index     = "index"
	Key       = "key"
	Kind      = "kind"
	Loc       = "loc"
	Opts      = "opts"
	Path      = "path"
	Pid       = "pid"
	Query     = "query"
	SLQ       = "slq"
	SQL       = "sql"
	Src       = "src"
	ScanType  = "scan_type"
	Schema    = "schema"
	Table     = "table"
	Target    = "target"
	To        = "to"
	Type      = "type"
	Line      = "line"
	URL       = "url"
	Val       = "value"
	Via       = "via"
	Version   = "version"
	Timestamp = "timestamp"
	Text      = "text"
)
