// Package lga ("log attribute") holds constants for log attribute
// names.
package lga

const (
	Alt       = "alt"
	Cmd       = "cmd"
	Col       = "column"
	Count     = "count"
	Cleanup   = "cleanup"
	DB        = "db"
	DBType    = "db_type"
	Driver    = "driver"
	DefaultTo = "default_to"
	Elapsed   = "elapsed"
	Err       = "error"
	From      = "from"
	Handle    = "handle"
	Key       = "key"
	Kind      = "kind"
	Loc       = "loc"
	Opts      = "opts"
	Path      = "path"
	Query     = "query"
	SLQ       = "slq"
	SQL       = "sql"
	Src       = "src"
	ScanType  = "scan_type"
	Table     = "table"
	Target    = "target"
	To        = "to"
	Type      = "type"
	Line      = "line"
	Val       = "value"
	Text      = "text"
)
