// Package lga ("log attribute") holds constants for log attribute
// names.
package lga

const (
	Action    = "action"
	After     = "after"
	Alt       = "alt"
	Before    = "before"
	Catalog   = "catalog"
	Cmd       = "cmd"
	Col       = "column"
	Count     = "count"
	Commit    = "commit"
	Conn      = "conn"
	Copied    = "copied"
	Cleanup   = "cleanup"
	DB        = "db"
	DBType    = "db_type"
	Dest      = "dest"
	Driver    = "driver"
	DefaultTo = "default_to"
	Elapsed   = "elapsed"
	Env       = "env"
	Err       = "error"
	Expected  = "expected"
	File      = "file"
	From      = "from"
	Flag      = "flag"
	Handle    = "handle"
	Index     = "index"
	Key       = "key"
	Kind      = "kind"
	Loc       = "loc"
	Lock      = "lock"
	Name      = "name"
	New       = "new"
	Old       = "old"
	Opts      = "opts"
	Path      = "path"
	Pid       = "pid"
	Query     = "query"
	Size      = "size"
	SLQ       = "slq"
	SQL       = "sql"
	Src       = "src"
	ScanType  = "scan_type"
	Schema    = "schema"
	Table     = "table"
	Target    = "target"
	To        = "to"
	Type      = "type"
	Line      = "line"
	URL       = "url"
	Val       = "value"
	Via       = "via"
	Version   = "version"
	Timestamp = "timestamp"
	Text      = "text"
)
